### ISSUE TITLE
Physical dimensions: Y is read as YES witch again is read as TRUE when importing in R

### ISSUE THREAD

**Issue by oodegard** [tischi/fiji-plugin-yaml-metadata#12]
Physical dimensions: Y is read as YES witch again is read as TRUE when importing in R

when loading using the command
yaml.load(paste0(readLines(yaml_path[i]), collapse = "\n"))

# Input
```yaml
!!de.embl.cba.metadata.MetaData
metadata:
  Total data size: 744 Mb
  Image dimensions: 2048x2048x31x3x1
  Physical dimensions:
    X: 0.10378323087160894 µm
    Y: 0.10378323087160894 µm
    Z: 0.3 µm
    T: NA
  Channels:
    Channel 0:
      Entity: NA
      Label: NA
    Channel 1:
      Entity: NA
      Label: NA
    Channel 2:
      Entity: NA
      Label: NA
  Time points:
  - Time_00001
  Positions:
  - Pos_00001
  Species:
    Name: NA
    Taxon: NA
  Imaging method: NA
  Developmental stage: NA
  Cell line: NA
````

# Read to R
```
$`metadata`$`Physical dimensions`
$`metadata`$`Physical dimensions`$`X`
[1] "0.10378323087160894 µm"
$`metadata`$`Physical dimensions`$`TRUE`
[1] "0.10378323087160894 µm"
$`metadata`$`Physical dimensions`$Z
[1] "0.3 µm"
$`metadata`$`Physical dimensions`$T
[1] "NA"
```

**Comment by oodegard** [comment]
Maybe we could avoid problems in parsers if we add quotation marks to the keys?

```yaml
  Physical dimensions:
    `X`: 0.10378323087160894 µm
    `Y`: 0.10378323087160894 µm
    `Z`: 0.3 µm
    `T`: NA
```
Since this fixes the problem for me now.
I have reported this but in the R yaml package, but I do not know how long it will take to fix this.

**Comment by oodegard** [comment]
R yaml will not change this until  LibYAML (http://pyyaml.org/wiki/LibYAML), updates to YAML 1.2.
[https://github.com/viking/r-yaml/issues/5#issuecomment-48543465](https://github.com/viking/r-yaml/issues/5#issuecomment-48543465)




A workaround for now is
yaml.load(paste0(readLines(yaml_path[i])), handlers=list('bool#yes' = function(x) { if (x == "Y") x else TRUE}))

**Comment by tischi** [comment]
@jkh1 @oodegard 
I hate R trying to be smart when reading text files. I had a similar issue with the letter "F" (=`FALSE`) which I needed for high trough-put microscopy plate coordinates. Maybe JK has some other ideas?

**Comment by jkh1** [comment]
The only thing that would always work is to always quote keys. This is probably the best approach since the issue of evaluating 'naked' strings could also crop up in other languages.
With respect to the R yaml package, I consider this a bug because the doc states that all keys are considered as strings which is clearly false since F and Y as keys are not treated as strings.

**Comment by tischi** [comment]
@oodegard 
Which YAML mode are you using? `Auto`, `Block`, or `Flow`?

**Comment by oodegard** [comment]
I am using Block mode since I originally thought the Auto mode was the reson for the error. R always uses Block mode.

**Comment by oodegard** [comment]
After reading into R with:
```R
yaml.load(paste0(readLines(yaml_path[i])), handlers=list('bool#yes' = function(x) { if (x == "Y") x else TRUE}))
```
And then saving the yaml file. I get this output. Allthough the µm unit is messed up, the Y has been quoted:

```yaml
Physical dimensions:
    X: 0.10378323087160894 Âµm
    'Y': 0.10378323087160894 Âµm
    Z: 0.3 Âµm
    T: NA
```

But I guess that we could just allways add a quote. That way we never have this problem again.
